# Generated by LakehousePlumber
# Pipeline: dep_bindings
# FlowGroup: configured_union_flow

from pyspark import pipelines as dp
from custom_python_functions.dep_bindings_union_transform import union_configured_tables

# Pipeline Configuration
PIPELINE_ID = "dep_bindings"
FLOWGROUP_ID = "configured_union_flow"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_union_seed():
    """Delta source: acme_edw_dev.edw_raw.dep_bindings_seed"""
    df = spark.readStream.table("acme_edw_dev.edw_raw.dep_bindings_seed")

    return df


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================


@dp.temporary_view()
def v_union_out():
    """Python transform: dep_bindings_union_transform.union_configured_tables"""
    # Load source view(s)
    v_union_seed_df = spark.readStream.table("v_union_seed")

    # Apply Python transformation
    parameters = {
        "tables": [
            "acme_edw_dev.edw_bronze.dep_loop_alpha",
            "acme_edw_dev.edw_bronze.dep_loop_beta",
        ]
    }
    df = union_configured_tables(v_union_seed_df, spark, parameters)

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_silver.configured_union",
    comment="Streaming table: configured_union",
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_silver.configured_union",
    name="f_union_out",
    comment="Append flow to acme_edw_dev.edw_silver.configured_union",
)
def f_union_out():
    """Append flow to acme_edw_dev.edw_silver.configured_union"""
    # Streaming flow
    df = spark.readStream.table("v_union_out")

    return df
