# Generated by LakehousePlumber
# Pipeline: custom_datasource
# FlowGroup: custom_with_metadata

from pyspark import cloudpickle as _lhp_cloudpickle
from pyspark.sql import functions as F
from pyspark import pipelines as dp
from custom_python_functions.api_with_wildcard import APIWithWildcardSource
import custom_python_functions

_lhp_cloudpickle.register_pickle_by_value(custom_python_functions)

# Pipeline Configuration
PIPELINE_ID = "custom_datasource"
FLOWGROUP_ID = "custom_with_metadata"


# ============================================================================
# SOURCE VIEWS
# ============================================================================

# Try to register the custom data source
try:
    spark.dataSource.register(APIWithWildcardSource)
except Exception:
    pass  # Ignore if already registered


@dp.temporary_view()
def v_custom_api_data():
    """Load data from custom API source with wildcard imports"""
    df = (
        spark.readStream.format("api_wildcard")
        .option("endpoint", "https://api.example.com")
        .load()
    )

    # Add operational metadata columns
    df = df.withColumn("_processing_timestamp", F.current_timestamp())

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_bronze.custom_api_data_bob",
    comment="Streaming table: custom_api_data_bob",
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_bronze.custom_api_data_bob",
    name="f_custom_api_data",
    comment="Write custom API data to streaming table",
)
def f_custom_api_data():
    """Write custom API data to streaming table"""
    # Streaming flow
    df = spark.readStream.table("v_custom_api_data")

    return df
