# Generated by LakehousePlumber
# Pipeline: custom_datasource
# FlowGroup: sink_with_metadata

from pyspark import cloudpickle as _lhp_cloudpickle
from pyspark.sql import functions as F
from pyspark import pipelines as dp
from custom_python_functions.custom_sink_wildcard import CustomSinkWithWildcard
import custom_python_functions

_lhp_cloudpickle.register_pickle_by_value(custom_python_functions)

# Pipeline Configuration
PIPELINE_ID = "custom_datasource"
FLOWGROUP_ID = "sink_with_metadata"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_test_sink_data():
    """Load test data for sink testing"""
    df = spark.sql("""SELECT 1 as id, 'test' as name, 100 as value""")

    # Add operational metadata columns
    df = df.withColumn("_processing_timestamp", F.current_timestamp())

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Write to custom sink with wildcard imports and operational metadata

# Register custom data sink
try:
    spark.dataSource.register(CustomSinkWithWildcard)
except Exception:
    pass  # Already registered

# Create custom sink
dp.create_sink(
    name="custom_wildcard_sink",
    format="custom_sink_wildcard",
    options={"output_path": "/tmp/custom_sink_output"},
)


# Define append flow(s)
@dp.append_flow(
    target="custom_wildcard_sink",
    name="f_custom_wildcard_sink_1",
    comment="""Write to custom sink with wildcard imports and operational metadata""",
)
def f_custom_wildcard_sink_1():
    df = spark.readStream.table("v_test_sink_data")

    # Add operational metadata columns
    df = df.withColumn("_processing_timestamp", F.current_timestamp())

    return df
