# LHP-SOURCE: py_functions/helper_demo_snapshot.py
# Generated by LakehousePlumber - DO NOT EDIT
# Changes will be overwritten on next generation

"""Entry module (snapshot-CDC ``source_function`` / write funnel) for the fixture.

The snapshot source function imports the local helper ``helpers.aggregate``
(whose own ``from helpers.other import tag`` is a transitive ABSOLUTE
helper->helper import). LHP copies the entry + the helper closure into
``custom_python_functions/`` and prefix-rewrites the entry's
``from helpers.aggregate import aggregate_rows`` to the
``custom_python_functions.`` form; the snapshot driver imports this module via
``import custom_python_functions.helper_demo_snapshot as _snap_…``.
"""

from typing import Optional, Tuple

from pyspark.sql import DataFrame

from custom_python_functions.helpers.aggregate import aggregate_rows


def next_helper_snapshot(
    latest_snapshot_version: Optional[int],
) -> Optional[Tuple[DataFrame, int]]:
    """Return the first snapshot once, enriched via the helper closure."""
    if latest_snapshot_version is not None:
        return None
    rows = [(1, "  alpha  "), (2, "  beta  ")]
    df = spark.createDataFrame(rows, schema="id INT, name STRING")  # noqa: F821
    return (aggregate_rows(df), 1)
