# Generated by LakehousePlumber
# Pipeline: 13_sinks
# FlowGroup: sk_delta

from pyspark.sql import functions as F
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "13_sinks"
FLOWGROUP_ID = "sk_delta"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_metrics_delta_sink():
    """Load fact_orders for streaming export to Delta sink"""
    df = spark.readStream.table("acme_edw_dev.edw_silver.fact_orders")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Stream daily order metrics to shared analytics catalog

# Create Delta sink
dp.create_sink(
    name="analytics_delta_export",
    format="delta",
    options={
        "tableName": "acme_edw_dev.edw_analytics.daily_order_metrics_bob",
        "checkpointLocation": "/Volumes/acme_edw_dev/_meta/checkpoints/sk_delta_export",
        "mergeSchema": "true",
    },
)


# Define append flow(s)
@dp.append_flow(
    target="analytics_delta_export",
    name="f_analytics_delta_export_1",
    comment="Stream daily order metrics to shared analytics catalog",
)
def f_analytics_delta_export_1():
    df = spark.readStream.table("v_metrics_delta_sink")

    return df
