# Generated by LakehousePlumber
# Pipeline: 13_sinks
# FlowGroup: sk_foreach_batch

from pyspark.sql import functions as F
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "13_sinks"
FLOWGROUP_ID = "sk_foreach_batch"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_customer_changes():
    """Load customer dim CDC stream for foreach_batch merge"""
    df = spark.readStream.table("acme_edw_dev.edw_silver.dim_customer")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Per-batch MERGE into target customer dimension


@dp.foreach_batch_sink(name="customer_merge_sink")
def customer_merge_sink(df, batch_id):
    """ForEachBatch sink: merge_customer_updates"""
    df.createOrReplaceTempView("batch_view")
    df.sparkSession.sql("""
        MERGE INTO acme_edw_dev.edw_gold.dim_customer_merged AS tgt
        USING batch_view AS src
        ON tgt.customer_id = src.customer_id
        WHEN MATCHED THEN
            UPDATE SET tgt.name = src.name
        WHEN NOT MATCHED THEN
            INSERT (customer_id, name)
            VALUES (src.customer_id, src.name)
    """)

    return


@dp.append_flow(
    target="customer_merge_sink",
    name="f_customer_merge_sink_1",
    comment="ForEachBatch sink: merge_customer_updates",
)
def f_customer_merge_sink_1():
    df = spark.readStream.table("v_customer_changes")

    return df
