# Generated by LakehousePlumber
# Pipeline: 13_sinks
# FlowGroup: sk_kafka

from pyspark.sql import functions as F
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "13_sinks"
FLOWGROUP_ID = "sk_kafka"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_orders_for_kafka_raw():
    """Load fact_orders for streaming to Kafka"""
    df = spark.readStream.table("acme_edw_dev.edw_silver.fact_orders")

    return df


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================


@dp.temporary_view(comment="SQL transform: prepare_kafka_message")
def v_orders_for_kafka():
    """SQL transform: prepare_kafka_message"""
    df = spark.sql("""SELECT
  CAST(order_id AS STRING) AS key,
  to_json(struct(
    order_id,
    customer_id,
    order_status,
    total_price,
    current_timestamp() AS event_timestamp
  )) AS value
FROM v_orders_for_kafka_raw""")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Stream order events to Kafka topic

# Create Kafka sink
dp.create_sink(
    name="order_events_kafka",
    format="kafka",
    options={
        "kafka.bootstrap.servers": "pkc-921jm.us-east-2.aws.confluent.cloud:9092",
        "topic": "acme.orders.fulfillment",
        "kafka.security.protocol": "SASL_SSL",
        "kafka.sasl.mechanism": "PLAIN",
        "kafka.sasl.jaas.config": f'kafkashaded.org.apache.kafka.common.security.plain.PlainLoginModule required username="{dbutils.secrets.get(scope="kafka_secrets", key="kafka_api_key")}" password="{dbutils.secrets.get(scope="kafka_secrets", key="kafka_api_secret")}";',
        "checkpointLocation": "/Volumes/acme_edw_dev/_meta/checkpoints/sk_kafka_export",
    },
)


# Define append flow(s)
@dp.append_flow(
    target="order_events_kafka",
    name="f_order_events_kafka_1",
    comment="Stream order events to Kafka topic",
)
def f_order_events_kafka_1():
    df = spark.readStream.table("v_orders_for_kafka")

    # Runtime validation for strict mode (user must provide key and value columns)
    if "value" not in df.columns:
        raise ValueError(
            "Kafka sink requires 'value' column in strict mode. Add a transform action to create it."
        )
    # Key column is optional for Kafka

    return df
