# Generated by LakehousePlumber
# Pipeline: uc_tagging_none
# FlowGroup: uc_no_tags

from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "uc_tagging_none"
FLOWGROUP_ID = "uc_no_tags"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_uc_sup():
    """Delta source: acme_edw_dev.edw_raw.supplier_raw"""
    df = spark.readStream.table("acme_edw_dev.edw_raw.supplier_raw")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_bronze.uc_supplier", comment="Streaming table: uc_supplier"
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_bronze.uc_supplier",
    name="f_supplier",
    comment="Append flow to acme_edw_dev.edw_bronze.uc_supplier",
)
def f_supplier():
    """Append flow to acme_edw_dev.edw_bronze.uc_supplier"""
    # Streaming flow
    df = spark.readStream.table("v_uc_sup")

    return df
