# Databricks notebook source
# Generated by Lakehouse Plumber — Monitoring Event Log Union
# This notebook runs N independent streaming queries (one per pipeline event log)
# into a single Delta table. Each stream has its own checkpoint directory,
# so adding or removing pipelines does not invalidate existing checkpoints.

from concurrent.futures import ThreadPoolExecutor, as_completed

from pyspark.sql import functions as F
from pyspark.sql.utils import AnalysisException

# ---------------------------------------------------------------------------
# Configuration (injected at generation time)
# ---------------------------------------------------------------------------
TARGET_TABLE = "acme_edw_dev._meta.unified_event_log"
CHECKPOINT_BASE = "/Volumes/acme_edw_dev/_meta/checkpoints/event_logs"
MAX_WORKERS = 10

SOURCES = [
    ("12_test_actions", "acme_edw_dev._meta.12_test_actions_event_log"),
    ("13_sinks", "acme_edw_dev._meta.13_sinks_event_log"),
    ("14_jdbc_load", "acme_edw_dev._meta.14_jdbc_load_event_log"),
    ("15_python_load", "acme_edw_dev._meta.15_python_load_event_log"),
    ("16_temp_table", "acme_edw_dev._meta.16_temp_table_event_log"),
    ("17_delta_cdc", "acme_edw_dev._meta.17_delta_cdc_event_log"),
    ("acme_edw_bp_bronze", "acme_edw_dev._meta.acme_edw_bp_bronze_event_log"),
    ("acme_edw_bp_raw", "acme_edw_dev._meta.acme_edw_bp_raw_event_log"),
    ("acme_edw_bp_silver", "acme_edw_dev._meta.acme_edw_bp_silver_event_log"),
    ("acmi_edw_bronze", "acme_edw_dev._meta.acmi_edw_bronze_event_log"),
    ("acmi_edw_modelled", "acme_edw_dev._meta.acmi_edw_modelled_event_log"),
    ("acmi_edw_raw", "acme_edw_dev._meta.acmi_edw_raw_event_log"),
    ("acmi_edw_silver", "acme_edw_dev._meta.acmi_edw_silver_event_log"),
    ("custom_datasource", "acme_edw_dev._meta.custom_datasource_event_log"),
    ("dep_bindings", "acme_edw_dev._meta.dep_bindings_event_log"),
    ("gold_load", "acme_edw_dev._meta.gold_load_event_log"),
    ("helper_imports", "acme_edw_dev._meta.helper_imports_event_log"),
    ("kafka_sample_pipeline", "acme_edw_dev._meta.kafka_sample_pipeline_event_log"),
    ("namespace_validation", "acme_edw_dev._meta.namespace_validation_event_log"),
    ("sample_python_func_pipeline", "acme_edw_dev._meta.sample_python_func_pipeline_event_log"),
    ("uc_tagging_core", "acme_edw_dev._meta.uc_tagging_core_event_log"),
    ("uc_tagging_mv", "acme_edw_dev._meta.uc_tagging_mv_event_log"),
    ("uc_tagging_none", "acme_edw_dev._meta.uc_tagging_none_event_log"),
]


# ---------------------------------------------------------------------------
# Prologue — pre-create the target table to avoid a cold-run CREATE race
# ---------------------------------------------------------------------------
# The parallel streaming queries below all call .toTable(TARGET_TABLE). On a
# cold run (target table does not yet exist), every worker races to CREATE
# the table; one wins, the rest fail with TABLE_OR_VIEW_ALREADY_EXISTS. We
# pre-create the table here using the schema of any readable source event
# log. Event-log schemas are uniform across DLT pipelines, and each stream
# uses mergeSchema=true to absorb any runtime-specific columns.
def _ensure_target_exists() -> None:
    """Pre-create TARGET_TABLE so parallel streams do not race on first run.

    Idempotent: no-op if the table already exists. Tries each source in
    SOURCES order until one event log is readable; raises RuntimeError only
    if no source is readable.
    """
    if spark.catalog.tableExists(TARGET_TABLE):  # noqa: F821
        return
    last_error: Exception | None = None
    for sample_name, sample_ref in SOURCES:
        try:
            empty = (
                spark.read.format("delta").table(sample_ref).limit(0)  # noqa: F821
                .withColumn("_source_pipeline", F.lit(sample_name))
            )
            empty.write.format("delta").saveAsTable(TARGET_TABLE)
            return
        except AnalysisException as exc:
            last_error = exc
            continue
    raise RuntimeError(
        f"Unable to create target table {TARGET_TABLE}: no source event log "
        f"readable among {[ref for _, ref in SOURCES]}. Last error: {last_error}"
    )


if SOURCES:
    _ensure_target_exists()


# ---------------------------------------------------------------------------
# Worker function — one independent streaming query per source
# ---------------------------------------------------------------------------
def process_source(pipeline_name: str, table_ref: str) -> str:
    """Run a single streaming query from table_ref into TARGET_TABLE.

    Each query gets its own checkpoint under CHECKPOINT_BASE/{pipeline_name}.
    Uses trigger(availableNow=True) so the query processes all available data
    and then terminates.
    """
    checkpoint = f"{CHECKPOINT_BASE}/{pipeline_name}"
    query = None
    try:
        query = (
            spark.readStream  # noqa: F821 — spark is provided by Databricks runtime
            .format("delta")
            .table(table_ref)
            .withColumn("_source_pipeline", F.lit(pipeline_name))
            .writeStream.format("delta")
            .outputMode("append")
            .option("checkpointLocation", checkpoint)
            .option("mergeSchema", "true")
            .trigger(availableNow=True)
            .toTable(TARGET_TABLE)
        )
        query.awaitTermination()
    except Exception:
        if query is not None:
            try:
                query.stop()
            except Exception:
                pass
        raise
    return pipeline_name


# ---------------------------------------------------------------------------
# Main execution — parallel streams with error collection
# ---------------------------------------------------------------------------
successes = []
failures = []

with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
    futures = {
        executor.submit(process_source, name, ref): name
        for name, ref in SOURCES
    }
    for future in as_completed(futures):
        pipeline_name = futures[future]
        try:
            future.result()
            successes.append(pipeline_name)
        except Exception as exc:
            failures.append((pipeline_name, str(exc)))

# Report results
summary_parts = [f"Processed {len(successes)}/{len(SOURCES)} event log streams."]
if successes:
    summary_parts.append(f"Succeeded: {', '.join(sorted(successes))}")
if failures:
    failure_details = "; ".join(
        f"{name}: {err}" for name, err in sorted(failures)
    )
    summary_parts.append(f"Failed: {failure_details}")

summary = " | ".join(summary_parts)

if failures:
    raise RuntimeError(
        f"Event log union failed for {len(failures)} pipeline(s): {summary}"
    )

dbutils.notebook.exit(summary)  # noqa: F821 — dbutils provided by Databricks runtime
