# ──────────────────────────────────────────────────────────────────────────────
# Unity Catalog Tagging Event Hook — uc_tagging_core
# Generated by Lakehouse Plumber — DO NOT EDIT
# ──────────────────────────────────────────────────────────────────────────────
#
# Applies UC tags to every managed table (and its columns) via the Entity Tag
# Assignments REST API, called through the Databricks SDK's raw api_client.do()
# interface (version-independent), because SQL tag-setting DDL is rejected inside
# pipeline execution.
#
# Tagging runs DURING the pipeline update (the event hook fires on update_progress
# RUNNING as well as the terminal states), so tag-write failures surface as pipeline
# event-log warnings while the run is still live. Streaming tables exist by RUNNING
# and are tagged then; materialized views (which materialise later) are tagged on the
# terminal pass. Each entity is attempted at most once (tracked in _processed).
#
# Existing tag state is read ONCE from system.information_schema (one query for all
# managed tables/columns) at MODULE IMPORT. Import only CATCHES a read failure (so it
# can never crash pipeline initialisation) and stashes it in _snapshot_error; the hook
# re-raises it on the first RUNNING event so it shows up as an event-log warning.
# Tagging is best-effort: it never fails the pipeline (event hooks cannot), and a
# missing snapshot degrades to create-only.

import json
import time
import urllib.parse
from concurrent.futures import ThreadPoolExecutor

from pyspark import pipelines as dp
from pyspark.sql import SparkSession

# fqn -> {tag_key: tag_value}
_TABLE_TAGS = {
    "acme_edw_dev.edw_bronze.uc_orders": {"team": "data-eng", "pii": "", "owner": ""}
}

# fqn -> {column_name: {tag_key: tag_value}}
_COLUMN_TAGS = {
    "acme_edw_dev.edw_bronze.uc_customers": {
        "c_email": {"classification": "pii", "masked": ""}
    }
}

_TAG_BASE = "/api/2.1/unity-catalog/entity-tag-assignments"
_REMOVE_UNDECLARED_TAGS = False

# Pipeline-level terminal states (update_progress). The terminal pass tags whatever
# is still untagged (e.g. materialized views that materialised after RUNNING).
_TERMINAL_PIPELINE_STATES = frozenset({"COMPLETED", "FAILED", "CANCELED", "STOPPING"})

# Error fragments that mean "the table isn't materialised yet" rather than a real
# tag failure. During RUNNING these are suppressed and the entity is retried later.
_ABSENT_MARKERS = ("does not exist", "not found", "resource_does_not_exist")

# Every fully-qualified table this hook manages (has table tags and/or column tags).
_MANAGED_FQNS = sorted(set(_TABLE_TAGS) | set(_COLUMN_TAGS))
# Lowercased fqn -> original; UC identifiers are case-insensitive and
# information_schema stores them lowercased (used to key the existing-tags snapshot).
_FQN_BY_LOWER = {fqn.lower(): fqn for fqn in _MANAGED_FQNS}

# Flat work-list of every managed entity: (entity_type, entity_name, desired_tags).
_WORK = [("table", fqn, tags) for fqn, tags in _TABLE_TAGS.items()] + [
    ("column", f"{fqn}.{column}", tags)
    for fqn, columns in _COLUMN_TAGS.items()
    for column, tags in columns.items()
]


def _fetch_existing_tags():
    """Read current UC tag state for all managed tables/columns in ONE query.

    A single ``table_tags UNION ALL column_tags`` query filters by
    **table name only**, via one outer ``WHERE table_key IN (...)`` so the managed
    table list is spelled out **once** (Catalyst pushes the predicate down through
    the union). It aggregates each entity's tags into a ``tags`` map and returns
    **one row per entity**. Entities with no tags simply don't appear — treated the
    same as having no tags. Returns
    ``{(entity_type, entity_name): {tag_name: tag_value}}`` (lowercased). Raises
    ``RuntimeError`` (with remediation guidance) on failure.
    """
    existing = {}
    if not _MANAGED_FQNS:
        return existing

    spark = SparkSession.builder.getOrCreate()

    # Filter on the RAW catalog_name / schema_name / table_name columns (NOT
    # lower()/concat expressions) so the metastore can prune to just the managed
    # catalogs/schemas — wrapping the filter columns in functions defeats pruning
    # and forces a scan of every catalog's tags. information_schema stores
    # identifiers lowercased, so the comparison values are lowercased to match.
    def _sql_in(values):
        return ", ".join("'" + v.replace("'", "''") + "'" for v in sorted(set(values)))

    catalogs = _sql_in(f.split(".")[0] for f in _FQN_BY_LOWER)
    schemas = _sql_in(".".join(f.split(".")[:2]) for f in _FQN_BY_LOWER)
    tables = _sql_in(_FQN_BY_LOWER)

    query = f"""
        SELECT entity_type, entity_name,
               map_from_entries(collect_list(struct(tag_name, tag_value))) AS tags
        FROM (
            SELECT 'table' AS entity_type, catalog_name,
                   concat_ws('.', catalog_name, schema_name) AS schema_name,
                   concat_ws('.', catalog_name, schema_name, table_name) AS table_name,
                   concat_ws('.', catalog_name, schema_name, table_name) AS entity_name,
                   tag_name, coalesce(tag_value, '') AS tag_value
            FROM system.information_schema.table_tags
            UNION ALL
            SELECT 'column' AS entity_type, catalog_name,
                   concat_ws('.', catalog_name, schema_name) AS schema_name,
                   concat_ws('.', catalog_name, schema_name, table_name) AS table_name,
                   concat_ws('.', catalog_name, schema_name, table_name, column_name) AS entity_name,
                   tag_name, coalesce(tag_value, '') AS tag_value
            FROM system.information_schema.column_tags
        )
        WHERE catalog_name IN ({catalogs})
          AND schema_name IN ({schemas})
          AND table_name IN ({tables})
        GROUP BY entity_type, entity_name
    """
    print(
        f"[LHP UC Tagging] Reading existing tag state from information_schema:\n{query}"
    )

    try:
        rows = spark.sql(query).collect()
    except Exception as e:
        raise RuntimeError(
            "[LHP UC Tagging] Failed to read existing tag state from "
            "system.information_schema (table_tags / column_tags). Grant the "
            "pipeline's run-as identity USE SCHEMA and SELECT on system.information_schema "
            f"(and USE CATALOG on `system`), then re-run. Original error: {e}"
        ) from e

    for row in rows:
        # Lowercase the key to match _apply's lookup (entity_name is no longer
        # lower()'d in SQL; a column's column_name segment may carry original case).
        key = (row["entity_type"], row["entity_name"].lower())
        existing[key] = dict(row["tags"] or {})
    return existing


# Snapshot of pre-existing tag state, keyed by (entity_type, lowercased entity_name).
# Read once at MODULE IMPORT — outside any @dp-decorated function, so the spark.sql
# .collect() does not trip the "DataFrame.collect inside a declarative pipelines
# decorated function" warning. A read failure is CAUGHT here (never crashes init) and
# stashed in _snapshot_error; the hook re-raises it on the first RUNNING event so the
# failure surfaces as a pipeline event-log warning. Tagging then degrades to
# create-only. Hooks run serially on the driver, so these module globals need no lock.
_existing_tags = {}
_snapshot_error = None
try:
    _existing_tags = _fetch_existing_tags()
except Exception as e:  # noqa: BLE001 — best-effort: stash, never warn/raise at import
    _snapshot_error = str(e)

# Set of entity_names already attempted, so an entity handled during RUNNING is not
# retried at terminal (per-entity, not a single pipeline-level flag). An entity is
# marked processed on success OR on a real failure — only "does not exist" (not yet
# materialised) is left out, so a later event retries it.
_processed = set()
# True once the snapshot-read warning has been surfaced (raised) once.
_snapshot_warned = False
# Set by the first terminal event so exactly one terminal pass runs.
_update_terminated = False

# Transient-error markers (case-insensitive substring match) that mean the REST call
# should be retried with backoff rather than reported as a tag failure.
_TRANSIENT_MARKERS = (
    "429",
    "too many requests",
    "rate limit",
    "throttl",
    "503",
    "service unavailable",
)
_MAX_TAG_ATTEMPTS = 4


def _do_with_retry(w, method, path, **kwargs):
    """Issue a single Entity-Tag REST call with bounded retry on TRANSIENT errors.

    Rate-limit (429) / service-unavailable (503) / throttling responses are retried up
    to ``_MAX_TAG_ATTEMPTS`` times with backoff (the server's ``retry_after_secs`` when
    present, else exponential, capped at 30s). NON-transient errors — including the
    "does not exist" absent markers and real permission failures — are re-raised
    immediately so the caller's existing handling is unchanged; the last transient
    error is re-raised once the attempt budget is exhausted.
    """
    for attempt in range(_MAX_TAG_ATTEMPTS):
        try:
            return w.api_client.do(method, path, **kwargs)
        except Exception as e:
            retry_after = getattr(e, "retry_after_secs", None)
            transient = retry_after is not None or any(
                m in str(e).lower() for m in _TRANSIENT_MARKERS
            )
            if not transient or attempt == _MAX_TAG_ATTEMPTS - 1:
                raise
            time.sleep(retry_after if retry_after is not None else min(2**attempt, 30))


def _reconcile_tags(w, entity_type, entity_name, existing, desired):
    """Create/update declared tags against the pre-fetched ``existing`` snapshot;
    delete undeclared ones when _REMOVE_UNDECLARED_TAGS is set. Additive otherwise.

    ``entity_type`` is the singular ``table``/``column``; the REST API expects the
    plural form, so we add the trailing 's' here at the API boundary.
    """
    rest_type = entity_type + "s"
    for key, value in desired.items():
        if key not in existing:
            _do_with_retry(
                w,
                "POST",
                _TAG_BASE,
                body={
                    "entity_type": rest_type,
                    "entity_name": entity_name,
                    "tag_key": key,
                    "tag_value": value,
                },
            )
        elif existing[key] != value:
            _do_with_retry(
                w,
                "PATCH",
                f"{_TAG_BASE}/{rest_type}/"
                f"{urllib.parse.quote(entity_name, safe='')}/tags/"
                f"{urllib.parse.quote(key, safe='')}",
                query={"update_mask": "tag_value"},
                body={
                    "entity_type": rest_type,
                    "entity_name": entity_name,
                    "tag_key": key,
                    "tag_value": value,
                },
            )

    if _REMOVE_UNDECLARED_TAGS:
        for key in existing:
            if key not in desired:
                _do_with_retry(
                    w,
                    "DELETE",
                    f"{_TAG_BASE}/{rest_type}/"
                    f"{urllib.parse.quote(entity_name, safe='')}/tags/"
                    f"{urllib.parse.quote(key, safe='')}",
                )


def _apply(w, suppress_absent):
    """Reconcile every not-yet-processed managed entity, in parallel.

    An entity is marked ``_processed`` on success **or** on a real failure, so the
    terminal pass never re-attempts it (which would surface a *duplicate* event-log
    warning, since terminal-time warnings appear with a delay after the update ends).
    The one exception is "table does not exist": when ``suppress_absent`` (the RUNNING
    pass) such an entity (e.g. a materialized view not yet materialised) is left
    un-processed and silent, so the terminal pass retries it. Real errors are returned
    as ``(entity_name, error)`` so the caller can surface them as a warning.
    """
    pending = [item for item in _WORK if item[1] not in _processed]
    errors = []

    def _do(item):
        entity_name = "<unknown>"  # fallback if the item itself is malformed
        try:
            entity_type, entity_name, desired = item
            existing = _existing_tags.get((entity_type, entity_name.lower()), {})
            _reconcile_tags(w, entity_type, entity_name, existing, desired)
        except Exception as e:  # noqa: BLE001 — collect real errors; handle "absent"
            if any(m in str(e).lower() for m in _ABSENT_MARKERS):
                # Not materialised yet → leave OUT of _processed so a later event
                # retries it. Silent during RUNNING; a genuine "missing" at terminal
                # is reported.
                if not suppress_absent:
                    errors.append((entity_name, e))
                return
            # Any other failure → report once, but mark processed so the terminal
            # pass does not re-attempt it and emit a duplicate warning.
            errors.append((entity_name, e))
            _processed.add(entity_name)  # set.add is atomic under the GIL
            return
        _processed.add(entity_name)  # success

    try:
        with ThreadPoolExecutor(max_workers=16) as executor:
            list(executor.map(_do, pending))
    except Exception as e:  # noqa: BLE001 — pool-level failure degrades to a warning
        errors.append(("<thread-pool>", e))

    return errors


# A run raises at most twice — one combined RUNNING warning (snapshot + tag errors)
# and one terminal warning — and the counter resets each update (the module re-imports
# per run), so 3 leaves headroom without ever silently disabling tagging on a clean run.
@dp.on_event_hook(max_allowable_consecutive_failures=3)
def uc_tagging_hook(event):
    """Tag managed tables/columns during the run, surfacing failures as warnings.

    Fires on update_progress:
      * ``RUNNING`` — tag everything that already exists (streaming tables). The event
        log is still capturing, so tag-write failures surface as warnings. A
        not-yet-materialised table ("does not exist") is suppressed and retried later.
      * the first terminal state — tag whatever is still untagged (e.g. materialized
        views that materialised after RUNNING). Guarded by ``_update_terminated`` so
        only one terminal pass runs.

    A snapshot-read failure stashed at import is re-raised here on the first RUNNING
    event, so it appears in the pipeline event-log warnings. Event hooks cannot fail a
    run — every raise here is a non-blocking warning. Per-entity ``_processed`` tracking
    keeps each entity reconciled at most once across all events.
    """
    global _snapshot_warned, _update_terminated
    if event.get("event_type") != "update_progress":
        return

    details = event.get("details", {})
    if isinstance(details, str):
        try:
            details = json.loads(details)
        except (ValueError, TypeError):
            return

    state = details.get("update_progress", {}).get("state")

    if state == "RUNNING":
        suppress_absent = True  # materialized views may not be materialised yet
    elif state in _TERMINAL_PIPELINE_STATES:
        if _update_terminated:
            return
        _update_terminated = True
        suppress_absent = False  # by terminal, every managed table should exist
    else:
        return

    from databricks.sdk import WorkspaceClient

    w = WorkspaceClient()
    msgs = []

    # Surface the snapshot-read failure (caught at import) once, during the run.
    if _snapshot_error is not None and not _snapshot_warned:
        _snapshot_warned = True
        msgs.append(
            "could not read existing tag state from system.information_schema; "
            f"creating all declared tags (updates/skips may not be detected). {_snapshot_error}"
        )

    errors = _apply(w, suppress_absent)
    if errors:
        detail = "; ".join(f"{name}: {err}" for name, err in errors)
        print(
            f"[LHP UC Tagging] ERROR: {len(errors)} tag operation(s) failed — {detail}"
        )
        msgs.append(f"{len(errors)} tag operation(s) failed — {detail}")

    if msgs:
        # One raise per event → recorded as a pipeline event-log warning; cannot fail
        # the run (event hooks are non-blocking).
        raise RuntimeError("[LHP UC Tagging] WARNING: " + "; ".join(msgs))
