# Generated by LakehousePlumber
# Pipeline: uc_tagging_core
# FlowGroup: uc_tag_orders

from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "uc_tagging_core"
FLOWGROUP_ID = "uc_tag_orders"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_uc_orders():
    """Delta source: acme_edw_dev.edw_raw.orders_raw"""
    df = spark.readStream.table("acme_edw_dev.edw_raw.orders_raw")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_bronze.uc_orders",
    comment="Streaming table: uc_orders",
    schema="""o_orderkey BIGINT NOT NULL, o_custkey BIGINT NOT NULL, o_totalprice DECIMAL(18,2)""",
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_bronze.uc_orders",
    name="f_orders",
    comment="Append flow to acme_edw_dev.edw_bronze.uc_orders",
)
def f_orders():
    """Append flow to acme_edw_dev.edw_bronze.uc_orders"""
    # Streaming flow
    df = spark.readStream.table("v_uc_orders")

    return df
