# Generated by LakehousePlumber
# Pipeline: uc_tagging_core
# FlowGroup: uc_tag_customers

from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "uc_tagging_core"
FLOWGROUP_ID = "uc_tag_customers"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_uc_cust():
    """Delta source: acme_edw_dev.edw_raw.customer_raw"""
    df = spark.readStream.table("acme_edw_dev.edw_raw.customer_raw")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_bronze.uc_customers",
    comment="Streaming table: uc_customers",
    schema="""c_custkey BIGINT NOT NULL, c_name STRING, c_email STRING""",
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_bronze.uc_customers",
    name="f_customers",
    comment="Append flow to acme_edw_dev.edw_bronze.uc_customers",
)
def f_customers():
    """Append flow to acme_edw_dev.edw_bronze.uc_customers"""
    # Streaming flow
    df = spark.readStream.table("v_uc_cust")

    return df
