# Generated by LakehousePlumber
# Pipeline: acmi_edw_silver
# FlowGroup: customer_silver_dim_backfill

from pyspark.sql import functions as F
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_silver"
FLOWGROUP_ID = "customer_silver_dim_backfill"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_customer_bronze_backfill():
    """Historical customer snapshot (batch, one-time)"""
    df = spark.read.table("acme_edw_dev.edw_bronze.customer")

    # Add operational metadata columns
    df = df.withColumn("_processing_timestamp", F.current_timestamp())

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# CDC flow: f_customer_silver_backfill
dp.create_auto_cdc_flow(
    target="acme_edw_dev.edw_silver.customer_dim_bob",
    source="v_customer_bronze_backfill",
    name="f_customer_silver_backfill",
    keys=["customer_id"],
    sequence_by="last_modified_dt",
    stored_as_scd_type=2,
    track_history_except_column_list=[
        "_source_file_path",
        "_processing_timestamp",
        "customer_key",
        "last_modified_dt",
    ],
    once=True,
    ignore_null_updates=False,
)
