# Generated by LakehousePlumber
# Pipeline: acmi_edw_silver
# FlowGroup: customer_dim_sfcc

from pyspark.sql import functions as F
from pyspark.sql.types import StructType
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_silver"
FLOWGROUP_ID = "customer_dim_sfcc"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_bronze_sfcc_cust():
    """Load customer data from bronze layer"""
    df = spark.readStream.table("acme_edw_dev.edw_bronze.bronze_sfcc_cust")

    return df


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================


@dp.temporary_view()
def v_customer_standardized():
    """Apply type casting to customer data (keep original column names)"""
    df = spark.readStream.table("v_bronze_sfcc_cust")

    # Apply column renaming
    df = df.withColumnRenamed("customer_id", "customer_id")
    df = df.withColumnRenamed("first_name", "first_name")
    df = df.withColumnRenamed("last_name", "last_name")
    df = df.withColumnRenamed("email", "email")
    df = df.withColumnRenamed("phone", "phone")
    df = df.withColumnRenamed("dob", "dob")
    df = df.withColumnRenamed("segment", "segment")
    df = df.withColumnRenamed("status", "status")
    df = df.withColumnRenamed("created_at", "created_at")
    df = df.withColumnRenamed("updated_at", "updated_at")
    df = df.withColumnRenamed("last_update_dttm", "last_update_dttm")

    # Apply type casting
    df = df.withColumn("customer_id", F.col("customer_id").cast("BIGINT"))
    df = df.withColumn("first_name", F.col("first_name").cast("STRING"))
    df = df.withColumn("last_name", F.col("last_name").cast("STRING"))
    df = df.withColumn("email", F.col("email").cast("STRING"))
    df = df.withColumn("phone", F.col("phone").cast("STRING"))
    df = df.withColumn("dob", F.col("dob").cast("DATE"))
    df = df.withColumn("segment", F.col("segment").cast("STRING"))
    df = df.withColumn("status", F.col("status").cast("STRING"))
    df = df.withColumn("created_at", F.col("created_at").cast("TIMESTAMP"))
    df = df.withColumn("updated_at", F.col("updated_at").cast("TIMESTAMP"))
    df = df.withColumn("last_update_dttm", F.col("last_update_dttm").cast("TIMESTAMP"))

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table for CDC
dp.create_streaming_table(
    name="acme_edw_dev.edw_silver.dim_sfcc_cust_bob",
    comment="Streaming table: dim_sfcc_cust_bob",
    table_properties={
        "delta.enableChangeDataFeed": "true",
        "table.type": "dimension",
        "scd.type": "2",
    },
)

# CDC flow: f_customer_dim_scd2
dp.create_auto_cdc_flow(
    target="acme_edw_dev.edw_silver.dim_sfcc_cust_bob",
    source="v_customer_standardized",
    name="f_customer_dim_scd2",
    keys=["customer_id"],
    sequence_by="last_update_dttm",
    stored_as_scd_type=2,
    track_history_except_column_list=[
        "_processing_timestamp",
        "_source_file_path",
        "created_at",
        "updated_at",
        "last_update_dttm",
    ],
)
