# Generated by LakehousePlumber
# Pipeline: acmi_edw_silver
# FlowGroup: partsupp_silver_dim

from pyspark import pipelines as dp
import custom_python_functions.partsupp_snapshot_func as _snap_partsupp_snapshot_func

_snap_partsupp_snapshot_func.dbutils = dbutils
_snap_partsupp_snapshot_func.spark = spark

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_silver"
FLOWGROUP_ID = "partsupp_silver_dim"


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table for snapshot CDC
dp.create_streaming_table(
    name="acme_edw_dev.edw_silver.partsupp_dim_bob",
    comment="Streaming table: partsupp_dim_bob",
)

# Snapshot CDC mode using create_auto_cdc_from_snapshot_flow
dp.create_auto_cdc_from_snapshot_flow(
    target="acme_edw_dev.edw_silver.partsupp_dim_bob",
    source=_snap_partsupp_snapshot_func.next_snapshot_and_version,
    keys=["part_id", "supplier_id"],
    stored_as_scd_type=2,
    track_history_except_column_list=[
        "_source_file_path",
        "_processing_timestamp",
        "snapshot_id",
        "partsupp_key",
        "last_modified_dt",
    ],
)
