# Generated by LakehousePlumber
# Pipeline: acmi_edw_silver
# FlowGroup: supplier_silver_dim

from functools import partial
from pyspark import pipelines as dp
import custom_python_functions.supplier_param_snapshot_func as _snap_supplier_param_snapshot_func

_snap_supplier_param_snapshot_func.dbutils = dbutils
_snap_supplier_param_snapshot_func.spark = spark

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_silver"
FLOWGROUP_ID = "supplier_silver_dim"


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table for snapshot CDC
dp.create_streaming_table(
    name="acme_edw_dev.edw_silver.supplier_dim_bob",
    comment="Streaming table: supplier_dim_bob",
)

# Snapshot CDC mode using create_auto_cdc_from_snapshot_flow
dp.create_auto_cdc_from_snapshot_flow(
    target="acme_edw_dev.edw_silver.supplier_dim_bob",
    source=partial(
        _snap_supplier_param_snapshot_func.next_supplier_snapshot,
        catalog="acme_edw_dev",
        schema="edw_bronze",
        table="supplier",
    ),
    keys=["supplier_id"],
    stored_as_scd_type=2,
    track_history_except_column_list=[
        "_source_file_path",
        "_processing_timestamp",
        "snapshot_id",
        "last_modified_dt",
    ],
)
