# Generated by LakehousePlumber
# Pipeline: dep_bindings
# FlowGroup: opaque_read_flow

from pyspark import pipelines as dp
from custom_python_functions.dep_bindings_opaque_transform import opaque_helper_read

# Pipeline Configuration
PIPELINE_ID = "dep_bindings"
FLOWGROUP_ID = "opaque_read_flow"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_opaque_seed():
    """Delta source: acme_edw_dev.edw_raw.dep_bindings_seed"""
    df = spark.readStream.table("acme_edw_dev.edw_raw.dep_bindings_seed")

    return df


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================


@dp.temporary_view()
def v_opaque_out():
    """Python transform: dep_bindings_opaque_transform.opaque_helper_read"""
    # Load source view(s)
    v_opaque_seed_df = spark.readStream.table("v_opaque_seed")

    # Apply Python transformation
    parameters = {"suffix": "region_lookup"}
    df = opaque_helper_read(v_opaque_seed_df, spark, parameters)

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_silver.opaque_read_out_bob",
    comment="Streaming table: opaque_read_out_bob",
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_silver.opaque_read_out_bob",
    name="f_opaque_out",
    comment="Append flow to acme_edw_dev.edw_silver.opaque_read_out_bob",
)
def f_opaque_out():
    """Append flow to acme_edw_dev.edw_silver.opaque_read_out_bob"""
    # Streaming flow
    df = spark.readStream.table("v_opaque_out")

    return df
