# Generated by LakehousePlumber
# Pipeline: dep_bindings
# FlowGroup: param_snapshot_flow

from functools import partial
from pyspark import pipelines as dp
import custom_python_functions.dep_bindings_snapshot_func as _snap_dep_bindings_snapshot_func

_snap_dep_bindings_snapshot_func.dbutils = dbutils
_snap_dep_bindings_snapshot_func.spark = spark

# Pipeline Configuration
PIPELINE_ID = "dep_bindings"
FLOWGROUP_ID = "param_snapshot_flow"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_param_snapshot_seed():
    """Delta source: acme_edw_dev.edw_raw.dep_bindings_seed"""
    df = spark.readStream.table("acme_edw_dev.edw_raw.dep_bindings_seed")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table for snapshot CDC
dp.create_streaming_table(
    name="acme_edw_dev.edw_silver.param_snapshot_dim_bob",
    comment="Streaming table: param_snapshot_dim_bob",
)

# Snapshot CDC mode using create_auto_cdc_from_snapshot_flow
dp.create_auto_cdc_from_snapshot_flow(
    target="acme_edw_dev.edw_silver.param_snapshot_dim_bob",
    source=partial(
        _snap_dep_bindings_snapshot_func.next_param_snapshot,
        source_table="acme_edw_dev.edw_bronze.helper_snapshot_dim_bob",
    ),
    keys=["id"],
    stored_as_scd_type=1,
)
