# Generated by LakehousePlumber
# Pipeline: 15_python_load
# FlowGroup: python_load_basic

from pyspark.sql import DataFrame
from pyspark import pipelines as dp
from custom_python_functions.api_extractor import extract_customer_data

# Pipeline Configuration
PIPELINE_ID = "15_python_load"
FLOWGROUP_ID = "python_load_basic"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_customer_extract():
    """Load customer data from external API via Python function"""
    # Call the external Python function with spark and parameters
    parameters = {
        "api_endpoint": "https://api.example.com/customers",
        "batch_size": 1000,
        "start_date": "2024-01-01",
    }
    df = extract_customer_data(spark, parameters)

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================


@dp.materialized_view(
    name="acme_edw_dev.edw_bronze.python_load_customers_bob",
    comment="Customers loaded via Python extractor function",
    table_properties={},
)
def python_load_customers_bob():
    """Write to acme_edw_dev.edw_bronze.python_load_customers_bob from multiple sources"""
    # Materialized views use batch processing
    df = spark.read.table("v_customer_extract")

    return df
