# Generated by LakehousePlumber
# Pipeline: helper_imports
# FlowGroup: helper_transform_flow

from pyspark.sql import DataFrame
from pyspark import pipelines as dp
from custom_python_functions.helper_demo_transform import transform_with_helper

# Pipeline Configuration
PIPELINE_ID = "helper_imports"
FLOWGROUP_ID = "helper_transform_flow"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_helper_seed():
    """Seed rows for the helper-backed transform"""
    df = spark.sql("""SELECT 1 AS id, '  alpha  ' AS name""")

    return df


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================


@dp.temporary_view()
def v_helper_enriched():
    """Enrich seed rows via the imported helper closure"""
    # Load source view(s)
    v_helper_seed_df = spark.read.table("v_helper_seed")

    # Apply Python transformation
    parameters = {"spark": "spark", "parameters": {}}
    df = transform_with_helper(v_helper_seed_df, spark, parameters)

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================


@dp.materialized_view(
    name="acme_edw_dev.edw_bronze.helper_enriched_bob",
    comment="Rows enriched via a transitive helper closure",
    table_properties={},
)
def helper_enriched_bob():
    """Write to acme_edw_dev.edw_bronze.helper_enriched_bob from multiple sources"""
    # Materialized views use batch processing
    df = spark.read.table("v_helper_enriched")

    return df
