# Generated by LakehousePlumber
# Pipeline: helper_imports
# FlowGroup: helper_sink_flow

from pyspark import cloudpickle as _lhp_cloudpickle
from pyspark.sql import functions as F
from pyspark import pipelines as dp
from custom_python_functions.helper_demo_sink import HelperBackedSink
import custom_python_functions

_lhp_cloudpickle.register_pickle_by_value(custom_python_functions)

# Pipeline Configuration
PIPELINE_ID = "helper_imports"
FLOWGROUP_ID = "helper_sink_flow"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_helper_sink_seed():
    """Seed rows for the helper-backed custom sink"""
    df = spark.sql("""SELECT 1 AS id, '  alpha  ' AS name""")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Write seed rows to a custom sink backed by a helper closure

# Register custom data sink
try:
    spark.dataSource.register(HelperBackedSink)
except Exception:
    pass  # Already registered

# Create custom sink
dp.create_sink(
    name="helper_backed_sink",
    format="helper_backed_sink",
    options={"output_path": "/tmp/helper_sink_output"},
)


# Define append flow(s)
@dp.append_flow(
    target="helper_backed_sink",
    name="f_helper_backed_sink_1",
    comment="""Write seed rows to a custom sink backed by a helper closure""",
)
def f_helper_backed_sink_1():
    df = spark.readStream.table("v_helper_sink_seed")

    return df
