# Generated by LakehousePlumber
# Pipeline: helper_imports
# FlowGroup: helper_snapshot_flow

from pyspark import pipelines as dp
import custom_python_functions.helper_demo_snapshot as _snap_helper_demo_snapshot

_snap_helper_demo_snapshot.dbutils = dbutils
_snap_helper_demo_snapshot.spark = spark

# Pipeline Configuration
PIPELINE_ID = "helper_imports"
FLOWGROUP_ID = "helper_snapshot_flow"


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table for snapshot CDC
dp.create_streaming_table(
    name="acme_edw_dev.edw_bronze.helper_snapshot_dim_bob",
    comment="Streaming table: helper_snapshot_dim_bob",
)

# Snapshot CDC mode using create_auto_cdc_from_snapshot_flow
dp.create_auto_cdc_from_snapshot_flow(
    target="acme_edw_dev.edw_bronze.helper_snapshot_dim_bob",
    source=_snap_helper_demo_snapshot.next_helper_snapshot,
    keys=["id"],
    stored_as_scd_type=1,
)
