# Generated by LakehousePlumber
# Pipeline: helper_imports
# FlowGroup: helper_source_flow

from pyspark import cloudpickle as _lhp_cloudpickle
from pyspark import pipelines as dp
from custom_python_functions.helper_demo_source import HelperBackedSource
import custom_python_functions

_lhp_cloudpickle.register_pickle_by_value(custom_python_functions)

# Pipeline Configuration
PIPELINE_ID = "helper_imports"
FLOWGROUP_ID = "helper_source_flow"


# ============================================================================
# SOURCE VIEWS
# ============================================================================

# Try to register the custom data source
try:
    spark.dataSource.register(HelperBackedSource)
except Exception:
    pass  # Ignore if already registered


@dp.temporary_view()
def v_helper_source_data():
    """Load data from a custom source backed by a helper closure"""
    df = (
        spark.readStream.format("helper_backed")
        .option("endpoint", "https://api.example.com")
        .load()
    )

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_bronze.helper_source_data_bob",
    comment="Streaming table: helper_source_data_bob",
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_bronze.helper_source_data_bob",
    name="f_helper_source_data",
    comment="Write helper-backed custom source data to a streaming table",
)
def f_helper_source_data():
    """Write helper-backed custom source data to a streaming table"""
    # Streaming flow
    df = spark.readStream.table("v_helper_source_data")

    return df
