# Generated by LakehousePlumber
# Pipeline: helper_imports
# FlowGroup: helper_load_flow

from pyspark.sql import DataFrame
from pyspark import pipelines as dp
from custom_python_functions.helper_demo_load import load_helper_rows

# Pipeline Configuration
PIPELINE_ID = "helper_imports"
FLOWGROUP_ID = "helper_load_flow"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_helper_loaded():
    """Load rows via a python function backed by the helper closure"""
    # Call the external Python function with spark and parameters
    parameters = {}
    df = load_helper_rows(spark, parameters)

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================


@dp.materialized_view(
    name="acme_edw_dev.edw_bronze.helper_loaded_bob",
    comment="Rows loaded via a python function backed by a helper closure",
    table_properties={},
)
def helper_loaded_bob():
    """Write to acme_edw_dev.edw_bronze.helper_loaded_bob from multiple sources"""
    # Materialized views use batch processing
    df = spark.read.table("v_helper_loaded")

    return df
