# Generated by LakehousePlumber
# Pipeline: acme_edw_bp_silver
# FlowGroup: site_alpha_customer_silver

from pyspark import pipelines as dp
import custom_python_functions.partsupp_snapshot_func as _snap_partsupp_snapshot_func

_snap_partsupp_snapshot_func.dbutils = dbutils
_snap_partsupp_snapshot_func.spark = spark

# Pipeline Configuration
PIPELINE_ID = "acme_edw_bp_silver"
FLOWGROUP_ID = "site_alpha_customer_silver"


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table for snapshot CDC
dp.create_streaming_table(
    name="acme_edw_dev.edw_silver.site_alpha_customer_dim_bob",
    comment="Streaming table: site_alpha_customer_dim_bob",
    table_properties={"delta.enableRowTracking": "true"},
)

# Snapshot CDC mode using create_auto_cdc_from_snapshot_flow
dp.create_auto_cdc_from_snapshot_flow(
    target="acme_edw_dev.edw_silver.site_alpha_customer_dim_bob",
    source=_snap_partsupp_snapshot_func.next_snapshot_and_version,
    keys=["customer_id"],
    stored_as_scd_type=2,
    track_history_except_column_list=["_processing_timestamp"],
)
