# LHP-SOURCE: py_functions/helpers/sub/__init__.py
# Generated by LakehousePlumber - DO NOT EDIT
# Changes will be overwritten on next generation

"""Nested sub-package for the helper-copying E2E fixture.

Proves the closure copies a nested sub-package with its directory structure
preserved (``helpers/sub/deep.py`` -> ``custom_python_functions/helpers/sub/deep.py``).
"""
