# LHP-SOURCE: pipelines/15_python_load/extractors/api_extractor.py
# Generated by LakehousePlumber - DO NOT EDIT
# Changes will be overwritten on next generation

"""B5.2 fixture extractor — Python load function for E2E testing.

Returns a small in-memory DataFrame so the generated pipeline is exercisable
without external API calls. The Python load generator (LHP v0.8.6+) copies
this file into ``custom_python_functions/`` next to the generated pipeline
output and imports the function via
``from custom_python_functions.api_extractor import extract_customer_data``.
"""

from pyspark.sql import DataFrame, SparkSession


def extract_customer_data(spark: SparkSession, parameters: dict) -> DataFrame:
    """Extract a small synthetic customer DataFrame for testing.

    The real-world implementation would call an API using ``parameters``
    (e.g., ``api_endpoint``, ``batch_size``, ``start_date``); for E2E
    generation tests, we just return an in-memory DataFrame so the
    generated module can be imported and executed in any environment.
    """
    api_endpoint = parameters.get("api_endpoint")
    batch_size = parameters.get("batch_size", 100)
    start_date = parameters.get("start_date", "2024-01-01")

    rows = [
        (1, "alice", "alice@example.com", start_date),
        (2, "bob", "bob@example.com", start_date),
    ]
    schema = (
        "customer_id INT, first_name STRING, email STRING, registration_date STRING"
    )
    return spark.createDataFrame(rows, schema=schema)
