# Generated by LakehousePlumber
# Pipeline: uc_tagging_mv
# FlowGroup: uc_tag_mv_second

from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "uc_tagging_mv"
FLOWGROUP_ID = "uc_tag_mv_second"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_uc_nation():
    """Delta source: acme_edw_dev.edw_raw.nation_raw"""
    df = spark.readStream.table("acme_edw_dev.edw_raw.nation_raw")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_silver.uc_nation", comment="Streaming table: uc_nation"
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_silver.uc_nation",
    name="f_nation",
    comment="Append flow to acme_edw_dev.edw_silver.uc_nation",
)
def f_nation():
    """Append flow to acme_edw_dev.edw_silver.uc_nation"""
    # Streaming flow
    df = spark.readStream.table("v_uc_nation")

    return df
