# Generated by LakehousePlumber
# Pipeline: uc_tagging_mv
# FlowGroup: uc_tag_mv

from pyspark.sql import DataFrame
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "uc_tagging_mv"
FLOWGROUP_ID = "uc_tag_mv"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_uc_part():
    """Delta source: acme_edw_dev.edw_raw.part_raw"""
    df = spark.readStream.table("acme_edw_dev.edw_raw.part_raw")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================


@dp.materialized_view(
    name="acme_edw_dev.edw_gold.uc_part_summary",
    comment="Materialized view: uc_part_summary",
    table_properties={},
    schema="p_partkey BIGINT NOT NULL, p_name STRING, p_size INT",
)
def uc_part_summary():
    """Write to acme_edw_dev.edw_gold.uc_part_summary from multiple sources"""
    # Materialized views use batch processing
    df = spark.read.table("v_uc_part")

    return df
