# Generated by LakehousePlumber
# Pipeline: acme_edw_bp_bronze
# FlowGroup: site_beta_customer_bronze

from pyspark.sql import functions as F
from pyspark import pipelines as dp
from custom_python_functions.sample_func import transform_lrc_data_streaming

# Pipeline Configuration
PIPELINE_ID = "acme_edw_bp_bronze"
FLOWGROUP_ID = "site_beta_customer_bronze"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_site_beta_customer_raw():
    """Load site_beta customer raw stream"""
    df = spark.readStream.table("acme_edw_dev.edw_raw.site_beta_customer_raw")

    # Add operational metadata columns
    df = df.withColumn("_processing_timestamp", F.current_timestamp())

    return df


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================


@dp.temporary_view()
def v_site_beta_customer_cleansed():
    """Python transform: sample_func.transform_lrc_data_streaming"""
    # Load source view(s)
    v_site_beta_customer_raw_df = spark.readStream.table("v_site_beta_customer_raw")

    # Apply Python transformation
    parameters = {"spark": "spark", "parameters": {}}
    df = transform_lrc_data_streaming(v_site_beta_customer_raw_df, spark, parameters)

    # Add operational metadata columns
    df = df.withColumn("_processing_timestamp", F.current_timestamp())

    return df


# ============================================================================
# DATA QUALITY & QUARANTINE
# ============================================================================


# ----------------------------------------------------------------------------
# Expectations: v_site_beta_customer_cleansed → v_site_beta_customer_dqe
# ----------------------------------------------------------------------------


@dp.temporary_view()
# These expectations will fail the pipeline if violated
@dp.expect_all_or_fail(
    {
        "valid_custkey": "customer_id IS NOT NULL AND customer_id > 0",
        "valid_customer_name": "name IS NOT NULL AND LENGTH(TRIM(name)) > 0",
        "valid_nation_key": "nation_id IS NOT NULL AND nation_id >= 0",
    }
)
# These expectations will log warnings but not drop rows
@dp.expect_all(
    {
        "valid_phone_format": "phone IS NULL OR LENGTH(phone) >= 10",
        "valid_account_balance": "account_balance IS NULL OR account_balance >= -10000",
        "valid_market_segment": "market_segment IS NULL OR market_segment IN ('BUILDING', 'FURNITURE', 'HOUSEHOLD', 'MACHINERY')",
    }
)
def v_site_beta_customer_dqe():
    """Apply customer DQ checks for site_beta"""
    df = spark.readStream.table("v_site_beta_customer_cleansed")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_bronze.site_beta_customer_bob",
    comment="Streaming table: site_beta_customer_bob",
    table_properties={"delta.enableRowTracking": "true"},
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_bronze.site_beta_customer_bob",
    name="f_site_beta_customer_bronze",
    comment="Append flow to acme_edw_dev.edw_bronze.site_beta_customer_bob",
)
def f_site_beta_customer_bronze():
    """Append flow to acme_edw_dev.edw_bronze.site_beta_customer_bob"""
    # Streaming flow
    df = spark.readStream.table("v_site_beta_customer_dqe")

    return df
