# Generated by LakehousePlumber
# Pipeline: acmi_edw_silver
# FlowGroup: customer_silver_dim

from pyspark.sql import functions as F
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_silver"
FLOWGROUP_ID = "customer_silver_dim"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_customer_bronze():
    """Load customer table from silver schema"""
    df = spark.readStream.table("acme_edw_dev.edw_bronze.alice_customer")

    # Add operational metadata columns
    df = df.withColumn("_processing_timestamp", F.current_timestamp())

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table for CDC
dp.create_streaming_table(
    name="acme_edw_dev.edw_silver.alice_customer_dim",
    comment="Streaming table: alice_customer_dim",
    table_properties={"delta.enableRowTracking": "true"},
)

# CDC flow: f_customer_silver
dp.create_auto_cdc_flow(
    target="acme_edw_dev.edw_silver.alice_customer_dim",
    source="v_customer_bronze",
    name="f_customer_silver",
    keys=["customer_id"],
    sequence_by="last_modified_dt",
    stored_as_scd_type=2,
    track_history_except_column_list=[
        "_source_file_path",
        "_processing_timestamp",
        "customer_key",
        "last_modified_dt",
    ],
    ignore_null_updates=True,
)
