# Generated by LakehousePlumber
# Pipeline: acmi_edw_silver
# FlowGroup: nation_silver_dim

from pyspark.sql import functions as F
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_silver"
FLOWGROUP_ID = "nation_silver_dim"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_nation_bronze():
    """Load nation table from silver schema"""
    df = spark.readStream.table("acme_edw_dev.edw_bronze.nation")

    # Add operational metadata columns
    df = df.withColumn("_processing_timestamp", F.current_timestamp())

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_silver.alice_nation_dim",
    comment="Streaming table: alice_nation_dim",
    table_properties={"delta.enableRowTracking": "true"},
    cluster_by_auto=True,
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_silver.alice_nation_dim",
    name="f_nation_silver",
    comment="Append flow to acme_edw_dev.edw_silver.alice_nation_dim",
)
def f_nation_silver():
    """Append flow to acme_edw_dev.edw_silver.alice_nation_dim"""
    # Streaming flow
    df = spark.readStream.table("v_nation_bronze")

    return df
