# Generated by LakehousePlumber
# Pipeline: acmi_edw_bronze
# FlowGroup: local_variables_example

from pyspark.sql import functions as F
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_bronze"
FLOWGROUP_ID = "local_variables_example"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_test_customer_raw():
    """Load test_customer table from raw schema"""
    df = spark.readStream.table("acme_edw_dev.edw_raw.customer_raw")

    # Add operational metadata columns
    df = df.withColumn("_processing_timestamp", F.current_timestamp())

    return df


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================


@dp.temporary_view(comment="SQL transform: test_customer_cleanse")
def v_test_customer_cleaned():
    """SQL transform: test_customer_cleanse"""
    df = spark.sql("""SELECT * FROM v_test_customer_raw""")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_bronze.alice_test_customer",
    comment="Streaming table: alice_test_customer",
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_bronze.alice_test_customer",
    name="f_test_customer_bronze",
    comment="Append flow to acme_edw_dev.edw_bronze.alice_test_customer",
)
def f_test_customer_bronze():
    """Append flow to acme_edw_dev.edw_bronze.alice_test_customer"""
    # Streaming flow
    df = spark.readStream.table("v_test_customer_cleaned")

    return df
