# Generated by LakehousePlumber
# Pipeline: acmi_edw_bronze
# FlowGroup: quarantine_flow

from pyspark.sql import functions as F
from pyspark.sql.types import MapType, StringType
from pyspark.sql.window import Window
from pyspark import pipelines as dp
from delta.tables import DeltaTable

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_bronze"
FLOWGROUP_ID = "quarantine_flow"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_orders_raw():
    """Load orders from raw schema"""
    df = spark.readStream.table("acme_edw_dev.edw_raw.orders_raw")

    return df


# ============================================================================
# DATA QUALITY & QUARANTINE
# ============================================================================


# ----------------------------------------------------------------------------
# Quarantine: v_orders_raw → v_orders_validated
# ----------------------------------------------------------------------------

# --- Rules & constants ---

_EXPECTATIONS_v_orders_raw = {
    "valid_order_id": "order_id IS NOT NULL",
    "positive_amount": "order_amount > 0",
    "valid_customer_id": "customer_id IS NOT NULL",
}

_INVERSE_FILTER_v_orders_raw = (
    "NOT ((order_id IS NOT NULL) AND (order_amount > 0) AND (customer_id IS NOT NULL))"
)

_FAILED_RULE_EXPRS_v_orders_raw = [
    F.when(
        ~F.expr("order_id IS NOT NULL"),
        F.struct(
            F.lit("valid_order_id").alias("name"),
            F.lit("order_id IS NOT NULL").alias("rule"),
        ),
    ),
    F.when(
        ~F.expr("order_amount > 0"),
        F.struct(
            F.lit("positive_amount").alias("name"),
            F.lit("order_amount > 0").alias("rule"),
        ),
    ),
    F.when(
        ~F.expr("customer_id IS NOT NULL"),
        F.struct(
            F.lit("valid_customer_id").alias("name"),
            F.lit("customer_id IS NOT NULL").alias("rule"),
        ),
    ),
]

DLQ_TABLE_v_orders_raw = "acme_edw_dev.edw_bronze.universal_dlq"
DLQ_OUTBOX_TABLE_v_orders_raw = "acme_edw_dev.edw_bronze.universal_dlq_outbox"
SOURCE_TABLE_v_orders_raw = "acme_edw_dev.edw_bronze.orders"

_HASH_EXCLUDE_COLS_v_orders_raw = [
    "_flowgroup_name",
    "_ingestion_timestamp",
    "_pipeline_name",
    "_pipeline_run_id",
    "_processing_timestamp",
    "_source_file",
    "_source_file_path",
]

_EXPECTATIONS_RECYCLED_v_orders_raw = {
    "valid_order_id": "order_id IS NOT NULL",
    "positive_amount": "order_amount > 0",
    "valid_customer_id": "customer_id IS NOT NULL",
}


# --- Clean path (provides DQ metrics in event log) ---
@dp.temporary_view()
@dp.expect_all_or_drop(_EXPECTATIONS_v_orders_raw)
def _clean_v_orders_raw():
    """Apply quarantine data quality checks to orders — clean records"""
    return spark.readStream.table("v_orders_raw")


# --- Quarantine path (DLQ sink + routing) ---
@dp.foreach_batch_sink(name="dlq_sink_v_orders_raw")
def dlq_sink_v_orders_raw(batch_df, batch_id):
    """Write quarantined rows to DLQ table"""
    if batch_df.isEmpty():
        return

    spark = batch_df.sparkSession
    data_cols = [c for c in batch_df.columns if not c.startswith("_dlq")]
    _exclude = set(_HASH_EXCLUDE_COLS_v_orders_raw)
    hash_cols = [c for c in data_cols if c not in _exclude]

    batch = batch_df.withColumns(
        {
            "_row_json": F.to_json(F.struct(*hash_cols)),
            "_dlq_sk": F.xxhash64(
                F.lit(SOURCE_TABLE_v_orders_raw), F.to_json(F.struct(*hash_cols))
            ).cast("string"),
        }
    )

    if "_rescued_data" in batch_df.columns:
        _map_type = MapType(StringType(), StringType())
        variant_cols = [c for c in data_cols if c != "_rescued_data"]
        batch = (
            batch.withColumns(
                {
                    "_variant_json": F.when(
                        F.col("_rescued_data").isNotNull(),
                        F.to_json(
                            F.map_zip_with(
                                F.coalesce(
                                    F.from_json(
                                        F.to_json(F.struct(*variant_cols)), _map_type
                                    ),
                                    F.create_map(),
                                ),
                                F.map_filter(
                                    F.coalesce(
                                        F.from_json(F.col("_rescued_data"), _map_type),
                                        F.create_map(),
                                    ),
                                    lambda k, v: k != "_file_path",
                                ),
                                lambda k, v1, v2: F.coalesce(v2, v1),
                            )
                        ),
                    ).otherwise(F.to_json(F.struct(*variant_cols))),
                }
            )
            .withColumns(
                {
                    "_row_data": F.parse_json(F.col("_variant_json")),
                }
            )
            .withColumnRenamed("_rescued_data", "_dlq_rescued_data")
        )
    else:
        batch = batch.withColumns(
            {
                "_row_data": F.parse_json(F.to_json(F.struct(*data_cols))),
                "_dlq_rescued_data": F.lit(None).cast("string"),
            }
        )

    batch = batch.withColumns(
        {
            "_dlq_source_table": F.lit(SOURCE_TABLE_v_orders_raw),
            "_dlq_status": F.lit("quarantined"),
            "_dlq_timestamp": F.current_timestamp(),
        }
    ).select(
        "_dlq_sk",
        "_dlq_source_table",
        "_dlq_status",
        "_dlq_timestamp",
        "_dlq_failed_rules",
        "_dlq_rescued_data",
        "_row_data",
    )

    dlq = DeltaTable.forName(spark, DLQ_TABLE_v_orders_raw)
    (
        dlq.alias("dlq")
        .merge(batch.alias("new"), "dlq._dlq_sk = new._dlq_sk")
        .whenNotMatchedInsertAll()
        .execute()
    )
    return


@dp.append_flow(target="dlq_sink_v_orders_raw", name="quarantine_flow_v_orders_raw")
def quarantine_flow_v_orders_raw():
    """Route failed rows to DLQ"""
    return (
        spark.readStream.table("v_orders_raw")
        .filter(_INVERSE_FILTER_v_orders_raw)
        .withColumn(
            "_dlq_failed_rules",
            F.array_compact(F.array(*_FAILED_RULE_EXPRS_v_orders_raw)),
        )
    )


# --- Recycle path (dedup inbox → outbox) ---
@dp.foreach_batch_sink(name="recycle_sink_v_orders_raw")
def recycle_sink_v_orders_raw(batch_df, batch_id):
    """Deduplicate fixed DLQ rows and write to outbox"""
    if batch_df.isEmpty():
        return

    spark = batch_df.sparkSession
    w = Window.partitionBy("_dlq_sk").orderBy(F.desc("_commit_version"))
    deduped = (
        batch_df.withColumn("_rn", F.row_number().over(w))
        .filter("_rn = 1")
        .drop("_rn")
        .select(
            "_dlq_sk",
            "_dlq_source_table",
            "_row_data",
            F.current_timestamp().alias("_dlq_recycled_at"),
        )
    )

    outbox = DeltaTable.forName(spark, DLQ_OUTBOX_TABLE_v_orders_raw)
    (
        outbox.alias("out")
        .merge(deduped.alias("new"), "out._dlq_sk = new._dlq_sk")
        .whenNotMatchedInsertAll()
        .execute()
    )


@dp.append_flow(target="recycle_sink_v_orders_raw", name="recycle_flow_v_orders_raw")
def recycle_flow_v_orders_raw():
    """Read fixed rows from DLQ inbox via CDF"""
    return (
        spark.readStream.option("readChangeFeed", "true")
        .table(DLQ_TABLE_v_orders_raw)
        .filter(
            "_dlq_status = 'fixed' "
            "AND _change_type IN ('insert', 'update_postimage') "
            f"AND _dlq_source_table = '{SOURCE_TABLE_v_orders_raw}'"
        )
    )


# --- Recycled path (outbox → validated recycled view) ---
@dp.temporary_view()
@dp.expect_all_or_drop(_EXPECTATIONS_RECYCLED_v_orders_raw)
def _recycled_v_orders_raw():
    """Validate recycled rows from DLQ outbox"""
    clean = spark.readStream.table("_clean_v_orders_raw")
    return (
        spark.readStream.option("skipChangeCommits", "true")
        .table(DLQ_OUTBOX_TABLE_v_orders_raw)
        .filter(f"_dlq_source_table = '{SOURCE_TABLE_v_orders_raw}'")
        .select(
            [
                F.try_variant_get(
                    F.col("_row_data"), f"$.{field.name}", field.dataType.simpleString()
                ).alias(field.name)
                for field in clean.schema.fields
            ]
        )
    )


# --- Validated output (clean + recycled) ---
@dp.temporary_view()
def v_orders_validated():
    """Apply quarantine data quality checks to orders — clean + recycled records"""
    clean = spark.readStream.table("_clean_v_orders_raw")
    recycled = spark.readStream.table("_recycled_v_orders_raw")

    df = clean.union(recycled)

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_bronze.alice_orders_quarantined",
    comment="Streaming table: alice_orders_quarantined",
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_bronze.alice_orders_quarantined",
    name="f_orders_bronze",
    comment="Append flow to acme_edw_dev.edw_bronze.alice_orders_quarantined",
)
def f_orders_bronze():
    """Append flow to acme_edw_dev.edw_bronze.alice_orders_quarantined"""
    # Streaming flow
    df = spark.readStream.table("v_orders_validated")

    return df
